=== SeerAPI/api-data/data/v1/schemas/item_category/$id/index.json
{
  "$defs": {
    "ResourceRef_Item_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref",
      "x-model-name": "item"
    }
  },
  "properties": {
    "id": {
      "description": "资源ID",
      "title": "Id",
      "type": "integer"
    },
    "name": {
      "description": "物品分类名称",
      "title": "Name",
      "type": "string"
    },
    "max": {
      "description": "物品最大数量",
      "title": "Max",
      "type": "integer"
    },
    "item": {
      "description": "该分类下的所有物品",
      "items": {
        "$ref": "#/$defs/ResourceRef_Item_"
      },
      "title": "Item",
      "type": "array"
    },
    "hash": {
      "description": "数据哈希值，目前pydantic不支持对key进行排序，所以哈希值变化可能意味着数据结构变化而非数据值变化",
      "title": "Hash",
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "max",
    "hash"
  ],
  "title": "ItemCategory",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== SeerAPI/api-data/data/v1/data/item_category/25/index.json
{
  "id": 25,
  "name": "限时道具",
  "max": 9999,
  "item": [
    {
      "id": 2500015,
      "url": "https://api.seerapi.com/v1/item/2500015"
    },
    {
      "id": 2500014,
      "url": "https://api.seerapi.com/v1/item/2500014"
    },
    {
      "id": 2500013,
      "url": "https://api.seerapi.com/v1/item/2500013"
    },
    {
      "id": 2500012,
      "url": "https://api.seerapi.com/v1/item/2500012"
    },
    {
      "id": 2500011,
      "url": "https://api.seerapi.com/v1/item/2500011"
    },
    {
      "id": 2500010,
      "url": "https://api.seerapi.com/v1/item/2500010"
    },
    {
      "id": 2500009,
      "url": "https://api.seerapi.com/v1/item/2500009"
    },
    {
      "id": 2500008,
      "url": "https://api.seerapi.com/v1/item/2500008"
    },
    {
      "id": 2500007,
      "url": "https://api.seerapi.com/v1/item/2500007"
    },
    {
      "id": 2500006,
      "url": "https://api.seerapi.com/v1/item/2500006"
    },
    {
      "id": 2500005,
      "url": "https://api.seerapi.com/v1/item/2500005"
    },
    {
      "id": 2500004,
      "url": "https://api.seerapi.com/v1/item/2500004"
    },
    {
      "id": 2500003,
      "url": "https://api.seerapi.com/v1/item/2500003"
    },
    {
      "id": 2500002,
      "url": "https://api.seerapi.com/v1/item/2500002"
    },
    {
      "id": 2500001,
      "url": "https://api.seerapi.com/v1/item/2500001"
    }
  ],
  "hash": "e9e728a6"
}
