=== SeerAPI/api-data/data/v1/schemas/pet_effect/$id/index.json
{
  "$defs": {
    "EidEffectInUse": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/eid_effect_in_use/"
    },
    "ResourceRef_PetEffectGroup_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    }
  },
  "properties": {
    "id": {
      "description": "资源ID",
      "title": "Id",
      "type": "integer"
    },
    "name": {
      "description": "名称",
      "title": "Name",
      "type": "string"
    },
    "desc": {
      "description": "描述",
      "title": "Desc",
      "type": "string"
    },
    "effect": {
      "$ref": "#/$defs/EidEffectInUse",
      "description": "效果"
    },
    "star_level": {
      "description": "特性星级",
      "title": "Star Level",
      "type": "integer"
    },
    "effect_group": {
      "$ref": "#/$defs/ResourceRef_PetEffectGroup_",
      "description": "特性组资源引用，同特性的不同星级属于同一组"
    },
    "hash": {
      "description": "数据哈希值，目前pydantic不支持对key进行排序，所以哈希值变化可能意味着数据结构变化而非数据值变化",
      "title": "Hash",
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "desc",
    "effect",
    "star_level",
    "effect_group",
    "hash"
  ],
  "title": "PetEffect",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== SeerAPI/api-data/data/v1/data/pet_effect/1363/index.json
{
  "id": 1363,
  "name": "碎裂",
  "desc": "地面属性技能威力增加8%",
  "effect": {
    "effect_args": [
      7,
      7
    ],
    "effect": {
      "id": 28,
      "url": "https://api.seerapi.com/v1/eid_effect/28/"
    }
  },
  "star_level": 2,
  "effect_group": {
    "id": 7,
    "url": "https://api.seerapi.com/v1/pet_effect_group/7/"
  },
  "hash": "7c059e28"
}

=== SeerAPI/api-data/data/v1/data/pet_effect/1019/index.json
{
  "id": 1019,
  "name": "奇异",
  "desc": "神秘属性技能威力增加5%",
  "effect": {
    "effect_args": [
      14,
      5
    ],
    "effect": {
      "id": 28,
      "url": "https://api.seerapi.com/v1/eid_effect/28/"
    }
  },
  "star_level": 0,
  "effect_group": {
    "id": 14,
    "url": "https://api.seerapi.com/v1/pet_effect_group/14/"
  },
  "hash": "f02707c8"
}

=== SeerAPI/api-data/data/v1/data/pet_effect/1370/index.json
{
  "id": 1370,
  "name": "机能",
  "desc": "机械属性技能威力增加10%",
  "effect": {
    "effect_args": [
      6,
      8
    ],
    "effect": {
      "id": 28,
      "url": "https://api.seerapi.com/v1/eid_effect/28/"
    }
  },
  "star_level": 3,
  "effect_group": {
    "id": 6,
    "url": "https://api.seerapi.com/v1/pet_effect_group/6/"
  },
  "hash": "63552e46"
}
