=== SeerAPI/api-data/data/v1/schemas/pet_encyclopedia_entry/$id/index.json
{
  "$defs": {
    "ResourceRef_Pet_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    }
  },
  "properties": {
    "id": {
      "description": "精灵图鉴ID",
      "title": "Id",
      "type": "integer"
    },
    "name": {
      "description": "精灵名称",
      "title": "Name",
      "type": "string"
    },
    "has_sound": {
      "description": "精灵是否存在叫声",
      "title": "Has Sound",
      "type": "boolean"
    },
    "height": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "精灵身高，当这个值在图鉴中为'未知'时，这个值为null",
      "title": "Height"
    },
    "weight": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "精灵重量，当这个值在图鉴中为'未知'时，这个值为null",
      "title": "Weight"
    },
    "foundin": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "精灵发现地点",
      "title": "Foundin"
    },
    "food": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "精灵喜爱的食物",
      "title": "Food"
    },
    "introduction": {
      "description": "精灵介绍",
      "title": "Introduction",
      "type": "string"
    },
    "pet": {
      "$ref": "#/$defs/ResourceRef_Pet_",
      "description": "精灵"
    },
    "hash": {
      "description": "数据哈希值，目前pydantic不支持对key进行排序，所以哈希值变化可能意味着数据结构变化而非数据值变化",
      "title": "Hash",
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "has_sound",
    "introduction",
    "pet",
    "hash"
  ],
  "title": "PetEncyclopediaEntry",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== SeerAPI/api-data/data/v1/data/pet_encyclopedia_entry/3974/index.json
{
  "id": 3974,
  "name": "帕拉莫",
  "has_sound": false,
  "height": 900.0,
  "weight": 30.0,
  "foundin": null,
  "food": null,
  "introduction": "冰雪节盛大开幕,寒冰招募火热开启！海马一族的勇士闪亮登场，不知他的实力能否征服大家，让我们拭目以待吧！",
  "pet": {
    "id": 3974,
    "url": "https://api.seerapi.com/v1/pet/3974/"
  },
  "hash": "adcb178b"
}

=== SeerAPI/api-data/data/v1/data/pet_encyclopedia_entry/3842/index.json
{
  "id": 3842,
  "name": "丝萝",
  "has_sound": false,
  "height": 156.0,
  "weight": 42.0,
  "foundin": null,
  "food": null,
  "introduction": "2019年4月巅峰圣战精灵......“你就是我的紫罗兰，而哈娜星也是我们的哈娜星，不是我的哈娜星，对吧？”",
  "pet": {
    "id": 3842,
    "url": "https://api.seerapi.com/v1/pet/3842/"
  },
  "hash": "4e1bb76d"
}

=== SeerAPI/api-data/data/v1/data/pet_encyclopedia_entry/2322/index.json
{
  "id": 2322,
  "name": "克罗诺斯",
  "has_sound": true,
  "height": 200.0,
  "weight": 90.0,
  "foundin": null,
  "food": null,
  "introduction": "神秘而又强大的黑暗精灵！据说是某个组织的幕后主使，可以完美的操控暗影和神秘之力，可以将任何敌人玩弄于鼓掌之间！",
  "pet": {
    "id": 2322,
    "url": "https://api.seerapi.com/v1/pet/2322/"
  },
  "hash": "ad5dc205"
}
