=== SeerAPI/api-data/data/v1/schemas/universal_mintmark/$id/index.json
{
  "$defs": {
    "ResourceRef_MintmarkClassCategory_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    },
    "ResourceRef_MintmarkRarityCategory_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    },
    "ResourceRef_MintmarkTypeCategory_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    },
    "ResourceRef_Pet_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    },
    "SixAttributes": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/six_attributes/"
    }
  },
  "properties": {
    "type": {
      "$ref": "#/$defs/ResourceRef_MintmarkTypeCategory_",
      "description": "刻印类型"
    },
    "rarity": {
      "$ref": "#/$defs/ResourceRef_MintmarkRarityCategory_",
      "description": "刻印稀有度"
    },
    "pet": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/$defs/ResourceRef_Pet_"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "表示该刻印仅能安装在这些精灵上，null表示无精灵限制",
      "title": "Pet"
    },
    "id": {
      "description": "资源ID",
      "title": "Id",
      "type": "integer"
    },
    "name": {
      "description": "名称",
      "title": "Name",
      "type": "string"
    },
    "desc": {
      "description": "刻印描述",
      "title": "Desc",
      "type": "string"
    },
    "mintmark_class": {
      "anyOf": [
        {
          "$ref": "#/$defs/ResourceRef_MintmarkClassCategory_"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "刻印所属系列，当该刻印是精灵专属刻印时可能为null"
    },
    "base_attr_value": {
      "$ref": "#/$defs/SixAttributes",
      "description": "刻印基础属性值，仅当该刻印为全能刻印时有效"
    },
    "max_attr_value": {
      "$ref": "#/$defs/SixAttributes",
      "description": "刻印满级属性值，仅当该刻印为能力刻印或全能刻印时有效"
    },
    "extra_attr_value": {
      "anyOf": [
        {
          "$ref": "#/$defs/SixAttributes"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "刻印隐藏属性值，仅当该刻印为全能刻印并具有隐藏属性时有效"
    },
    "hash": {
      "description": "数据哈希值，目前pydantic不支持对key进行排序，所以哈希值变化可能意味着数据结构变化而非数据值变化",
      "title": "Hash",
      "type": "string"
    }
  },
  "required": [
    "type",
    "rarity",
    "id",
    "name",
    "desc",
    "base_attr_value",
    "max_attr_value",
    "hash"
  ],
  "title": "UniversalMintmark",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== SeerAPI/api-data/data/v1/data/universal_mintmark/40681/index.json
{
  "type": {
    "id": 3,
    "url": "https://api.seerapi.com/v1/mintmark_type/3/"
  },
  "rarity": {
    "id": 1,
    "url": "https://api.seerapi.com/v1/mintmark_rarity/1/"
  },
  "pet": [
    {
      "id": 3176,
      "url": "https://api.seerapi.com/v1/pet/3176/"
    }
  ],
  "id": 40681,
  "name": "魔齿鲨专属全能刻印",
  "desc": "体力+58,防御+20,特防+20,速度+20",
  "mintmark_class": null,
  "base_attr_value": {
    "atk": 0,
    "def": 2,
    "sp_atk": 0,
    "sp_def": 2,
    "spd": 2,
    "hp": 5,
    "percent": false,
    "total": 11
  },
  "max_attr_value": {
    "atk": 0,
    "def": 20,
    "sp_atk": 0,
    "sp_def": 20,
    "spd": 20,
    "hp": 58,
    "percent": false,
    "total": 118
  },
  "extra_attr_value": null,
  "hash": "745e1bfb"
}
