=== SeerAPI/api-data/data/v1/schemas/pet_class/$id/index.json
{
  "$defs": {
    "ResourceRef_Pet_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    }
  },
  "description": "描述一个精灵类别，所有第一形态为同一ID的精灵为一类",
  "properties": {
    "id": {
      "description": "资源ID",
      "title": "Id",
      "type": "integer"
    },
    "is_variant_pet": {
      "default": false,
      "description": "是否是异能精灵",
      "title": "Is Variant Pet",
      "type": "boolean"
    },
    "is_dark_pet": {
      "default": false,
      "description": "是否是暗黑精灵",
      "title": "Is Dark Pet",
      "type": "boolean"
    },
    "is_shine_pet": {
      "default": false,
      "description": "是否是闪光精灵",
      "title": "Is Shine Pet",
      "type": "boolean"
    },
    "is_rare_pet": {
      "default": false,
      "description": "是否是稀有精灵",
      "title": "Is Rare Pet",
      "type": "boolean"
    },
    "is_breeding_pet": {
      "default": false,
      "description": "是否是繁殖二代精灵",
      "title": "Is Breeding Pet",
      "type": "boolean"
    },
    "is_fusion_pet": {
      "default": false,
      "description": "是否是融合二代精灵",
      "title": "Is Fusion Pet",
      "type": "boolean"
    },
    "evolution_chain": {
      "description": "精灵进化链，从第一形态到最终形态的精灵列表",
      "items": {
        "$ref": "#/$defs/ResourceRef_Pet_"
      },
      "title": "Evolution Chain",
      "type": "array"
    },
    "hash": {
      "description": "数据哈希值，目前pydantic不支持对key进行排序，所以哈希值变化可能意味着数据结构变化而非数据值变化",
      "title": "Hash",
      "type": "string"
    }
  },
  "required": [
    "id",
    "evolution_chain",
    "hash"
  ],
  "title": "PetClass",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== SeerAPI/api-data/data/v1/data/pet_class/1354/index.json
{
  "id": 1354,
  "is_variant_pet": false,
  "is_dark_pet": false,
  "is_shine_pet": false,
  "is_rare_pet": false,
  "is_breeding_pet": false,
  "is_fusion_pet": false,
  "evolution_chain": [
    {
      "id": 2657,
      "url": "https://api.seerapi.com/v1/pet/2657/"
    }
  ],
  "hash": "8c9b1002"
}
