=== SeerAPI/api-data/data/v1/schemas/pet_archive_story_entry/$id/index.json
{
  "$defs": {
    "ResourceRef_PetArchiveStoryBook_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    },
    "ResourceRef_Pet_": {
      "$ref": "https://api.seerapi.com/v1/schemas/common/resource_ref/"
    }
  },
  "properties": {
    "id": {
      "description": "故事条目ID",
      "title": "Id",
      "type": "integer"
    },
    "content": {
      "description": "故事条目内容",
      "title": "Content",
      "type": "string"
    },
    "pet": {
      "$ref": "#/$defs/ResourceRef_Pet_",
      "description": "精灵"
    },
    "book": {
      "$ref": "#/$defs/ResourceRef_PetArchiveStoryBook_",
      "description": "故事"
    },
    "hash": {
      "description": "数据哈希值，目前pydantic不支持对key进行排序，所以哈希值变化可能意味着数据结构变化而非数据值变化",
      "title": "Hash",
      "type": "string"
    }
  },
  "required": [
    "id",
    "content",
    "pet",
    "book",
    "hash"
  ],
  "title": "PetArchiveStoryEntry",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== SeerAPI/api-data/data/v1/data/pet_archive_story_entry/501/index.json
{
  "id": 501,
  "content": "在里里维斯的一个兽人部落里，村民们意外发现了一件神秘的兵器，一把巨大的双刃刀，刀刃表面留有裂纹，一旦有人握住就会散发出炽烈的火光，有人猜测这是附着了神秘魔法的武器、有人则说这是之前村中勇士的遗物。恰好，盟会的长老此时路过了这个部落，兽人部落的村民们想要将发现的这件秘宝献给长老，但长老并没有接受，他认为这件武器是一件不祥之物，希望他们将它放回到原处。\\n长老的告诫让村里上下人心惶惶，这时，一位名为库坦的青年自告奋勇说要把武器送回去，但在此之前他试了试这把武器的手感，刀刃锋利，而且它并不像看上去那么厚重，可以用它轻松劈开很多东西。库坦提议，这么好的宝贝放回去太浪费了，不如加以利用。在说出这些话的时候，库坦的眼睛里散发出骇人的红色光辉，和平常的他不太一样。有人也附和着库坦希望留下这把武器，村民们陷入了争论之中。但不知什么时候，库坦已经消失了。他悄悄离开了村子。\\n……\\n没人知道库坦到底去哪里了，等到库坦再次现身在众人面前，已经是凌天城的城门爆炸的时候了。\\n他好似一个凶恶的屠夫，在坍塌的废墟一旁嘶吼，即使是身经百战的凌天将军彼尔德都没办法控制住他。随着鲜血从库坦的伤口流出，库坦手上的武器也散发出更加闪耀的炽光，似乎没有人可以阻止他…",
  "pet": {
    "id": 4503,
    "url": "https://api.seerapi.com/v1/pet/4503/"
  },
  "book": {
    "id": 2,
    "url": "https://api.seerapi.com/v1/pet_archive_story_book/2/"
  },
  "hash": "4fd7bfb0"
}

=== SeerAPI/api-data/data/v1/data/pet_archive_story_entry/279/index.json
{
  "id": 279,
  "content": "星魂的诞生，超出了任何人的预料。\\n打从有意识开始，他们便被这颗星球的无数生灵所景仰，所爱戴。在合适的时候醒来庇护这一方世界，在合适的时机沉睡放手这个世界使其自由发展。这便是星魂的使命。\\n也是星魂的诅咒。\\n玩笑似的赋予了他们生命，又玩笑似的剥夺了他们的自由。\\n这次醒来，又过去了多少年呢？\\n自己所熟知的使徒一个个都在时间的洪流中淹没，即使寿命足够，又有谁能够保证他自己能够在沉睡的星魂面前守候几次轮回呢？\\n到头来每次睁眼，都只剩下他一个人从这冰冷的坟墓中坐起身来。没人能和星魂生活在同一个时空之中，这是伽玛星魂不知在多少次沉睡后，得出的答案。\\n所以月照是幸运的，她既有忠心而长寿的使徒，也有着与自己一同醒来，一同沉睡的伴侣。\\n她也是懦弱的，满足于眼前短暂的幸福，而放弃了对自由的向往。伽玛星魂腻了，他不想再在醒来后于使徒的墓前叹息，也不想再看着曾立下誓言守候的人在光阴间黯然离去。\\n摒弃脑海中那最后一丝对和平的眷恋，他伸出手，握住了某个曾经妄图与宙理为敌的狂徒的遗物。如今，他也踏上了这条愚道。\\n精纯的能量透过暗君圣物涌入他的身体中，那种阴魂不散的困倦感在这一刻消失得无影无踪。\\n终于，有一位星魂，从那名为“沉眠”的无边地狱中，苏醒过来。\\n这或许是邪道，违背了宇宙的规则，也背叛了星球子民对他的希望，他很清楚。\\n但是自己已经不配，再提起那些了。\\n他不过是在使命与自由中，选择了后者。\\n即使他知道，那仅仅是被自私与屠戮所玷污的肮脏欲望。\\n仅此而已。",
  "pet": {
    "id": 3896,
    "url": "https://api.seerapi.com/v1/pet/3896/"
  },
  "book": {
    "id": 1,
    "url": "https://api.seerapi.com/v1/pet_archive_story_book/1/"
  },
  "hash": "8b67b61e"
}
